// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

var TableNames = struct {
	Admins   string
	Comments string
	Media    string
	Places   string
}{
	Admins:   "admins",
	Comments: "comments",
	Media:    "media",
	Places:   "places",
}
